name: Permissions
main: xyz.sethy.permissions.Main
authors: [Garispl, Seth McAllister]
version: 1.0-SNAPSHOT
commands:
  setrank:
  reloadgroups:
  addpermission:
    aliases: [addperm, grantperm, grantpermission]
  removepermission:
  permissionsinfo:
  addsubgroup:
  removesubgroup: